name: Test

on: ['push']

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Install scrot
        run: sudo apt install xterm xvfb scrot

      - name: Setup Xvfb
        run: Xvfb :99 -screen 1 800x800x16 &

      - name: Xterm
        run: DISPLAY=:99 xterm -maximized 2>/dev/null &

      - name: Test Screenshot
        run: DISPLAY=:99 scrot test.png

      - name: Save image
        uses: actions/upload-artifact@v3
        with:
          name: Screenshot
          path: test.png

